# Generated by Django 3.1.3 on 2021-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_typing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='average_wpm',
            field=models.IntegerField(default=0),
        ),
    ]
