# Generated by Django 3.1.3 on 2021-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210603_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='tests_taken',
            field=models.IntegerField(default=1),
        ),
    ]
