# Generated by Django 3.1.3 on 2021-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210603_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='average_wpm',
            field=models.IntegerField(),
        ),
    ]
