# Generated by Django 3.1.3 on 2021-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210603_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='average_wpm',
            field=models.IntegerField(default=50),
        ),
    ]
